class MatchStatus:
    OPEN = "OPEN"
    FULL = "FULL"
    READY = "READY"
    CONFIRMED = "CONFIRMED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class VenueStatus:
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class SkillLevel:
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"

    ALL = [BEGINNER, INTERMEDIATE, ADVANCED]